import {
  ChickenSkin1,
  ChickenSkin2,
  ChickenSkin3,
  MDM1,
  MDM2,
  MDM3,
  Mortadella1,
  Mortadella2,
  Mortadella3,
  Photo1,
  Photo2,
  Sausages1,
  Sausages2,
  Sausages3,
  DescMDM1,
  SizesMDM1,
  Pallet,
  Specs,
  Specs_3mm,
  DescMdm3mm,
  Baader_pallet,
  Desc_mort_classic,
  WhitePallet,
  Mortadella_packed,
  Desc_mort_italian,
  Mortadella_olives,
  Desc_mort_olives,
  Mortadella_packed_red,
  Mortadella_pepper,
  Sausages_packed,
  Desc_polish_sausages,
  Chorizo,
  Desc_chorizo,
  Desc_serdelka,
  Serdelka_packed,
  Salami_in_package,
  Desc_salami,
  Salami,
  Salchichas_packed,
  Salchichas,
  Spread,
  Chicken_spread,
  Desc_spread,
  Szynkovka,
  Szynkovka_pack,
  Desc_szynkovka,
  Desc_ham,
  Chicken_ham,
  Chicken_ham1,
  Picadillo,
  Picadillo_packed  

} from "../../img/index";

const dataProduct = [
  {
    id: 1,
    idCategory: 1,
    imgCategory: [MDM1,Specs,DescMDM1,SizesMDM1,Pallet],
    nameCategory: "Chicken MDM 1mm",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 2,
    idCategory: 1,
    imgCategory: [MDM2,Specs,DescMDM1,SizesMDM1,Pallet],
    nameCategory: "Chicken MDM 2mm",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 3,
    idCategory: 1,
    imgCategory: [MDM3,Specs_3mm,DescMdm3mm,SizesMDM1,Baader_pallet],
    nameCategory: "Chicken MDM 3mm",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 4,
    idCategory: 2,
    imgCategory: [ChickenSkin1,SizesMDM1],
    nameCategory: "Chicken",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 5,
    idCategory: 2,
    imgCategory: [ChickenSkin2,SizesMDM1],
    nameCategory: "Chicken Legs",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 6,
    idCategory: 2,
    imgCategory: [ChickenSkin3,SizesMDM1],
    nameCategory: "Chicken Wings",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 7,
    idCategory: 3,
    imgCategory: [Mortadella1,Desc_mort_classic,Mortadella_packed,WhitePallet],
    nameCategory: "Mortadella Classic",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 8,
    idCategory: 3,
    imgCategory: [Mortadella2,Desc_mort_italian,Mortadella_packed,WhitePallet],
    nameCategory: "Mortadella ala Italiana",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 9,
    idCategory: 3,
    imgCategory: [Mortadella_olives,Desc_mort_olives,Mortadella_packed_red,WhitePallet],
    nameCategory: "Mortadella with Olives",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 10,
    idCategory: 3,
    imgCategory: [Mortadella_pepper,Desc_mort_olives,Mortadella_packed_red,WhitePallet],
    nameCategory: "Mortadella with sweet pepper",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 11,
    idCategory: 4,
    imgCategory: [Sausages_packed,Sausages1,Salchichas,Salchichas_packed,Desc_polish_sausages,WhitePallet],
    nameCategory: "Polish chicken sausages",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id:12,
    idCategory: 4,
    imgCategory: [Sausages2,Chorizo,Desc_chorizo,WhitePallet],
    nameCategory: "Chorizo",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 13,
    idCategory: 4,
    imgCategory: [Sausages3,Serdelka_packed,Desc_serdelka,WhitePallet],
    nameCategory: "Polish Serdelka",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 14,
    idCategory: 4,
    imgCategory: [Salami,Salami_in_package,Desc_salami,WhitePallet],
    nameCategory: "Salami Classic",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 15,
    idCategory: 5,
    imgCategory: [Chicken_spread,Spread,Desc_spread,Mortadella_packed_red,WhitePallet],
    nameCategory: "Chicken sandwich spread",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 16,
    idCategory: 5,
    imgCategory: [Szynkovka,Szynkovka_pack,Desc_szynkovka,Mortadella_packed,WhitePallet],
    nameCategory: "Szynkovka",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 17,
    idCategory: 5,
    imgCategory: [Chicken_ham1,Chicken_ham,Desc_ham,WhitePallet],
    nameCategory: "Chicken breast ham",
    pacing1: Photo1,
    pacing2: Photo2,
  },
  {
    id: 18,
    idCategory: 5,
    imgCategory: [Picadillo,Picadillo_packed,WhitePallet],
    nameCategory: "Picadillo",
    pacing1: Photo1,
    pacing2: Photo2,
  },

];

export default dataProduct;
